DCS-736: user can now view the  page to change appointment time.
ministryofjustice/hmpps-book-video-link pull request #113
Opened 2021-01-08 09:39 UTC by GurnankCheema

As part of this change, the date formats inside input fields were changed to dd/mm/yyyy form rather than dd month year.
The bookingDetails object type now includes a dateDescription: string and  adate: moment type

2021-01-08 14:20 UTC, andrewrlee commented on backend/routes/amendBooking/changeDateAndTimeController.test.ts
> +        expect.objectContaining({
better not to use. `expect.objectContaining` for these kinds of tests - you really want to know exactly whats passed not just a subset of keys

2021-01-08 14:23 UTC, andrewrlee commented on backend/services/notificationService.test.ts
> +            date: moment('2020-11-20'),
this will break the email templates - the tests show the correct behavior, this should remain: `'20 November 2020',`

you need to update notificattion service to pass through dateDescription

2021-01-08 14:24 UTC, andrewrlee requested changes
Generally LGTM but still need to fix the notification service

2021-01-08 17:12 UTC, GurnankCheema commented on backend/services/notificationService.test.ts
> +            date: moment('2020-11-20'),
I see. 
I had changed the date to a moment incorrectly. Have reverted it back to a string and changed the notificationServices's personalisation.date to personalisation.dateDescription

2021-01-08 18:06 UTC, GurnankCheema commented on backend/routes/amendBooking/changeDateAndTimeController.test.ts
> +        expect.objectContaining({
changed

2021-01-11 10:35 UTC, GurnankCheema commented on backend/routes/amendBooking/selectAvailableRoomsController.ts
> +  private formatTime(date: Moment, time: string): string {
typescript error was being thrown when date was a defined as a string type

2021-01-11 13:05 UTC, andrewrlee commented on backend/routes/amendBooking/selectAvailableRoomsController.ts
> +  private formatTime(date: Moment, time: string): string {
So this was because previously a string was being passed back - if you read the code:

This parses the date from a string to a moment. 
`moment(date, 'D MMMM YYYY')`

Now you are passing through a `moment` we don't need to do the parsing, we can just format it directly into a string.

2021-01-11 15:24 UTC, andrewrlee approved these changes
LGTM

2021-01-11 15:27 UTC, merged